@startuml
'Alt + D to preview


left to right direction

:Player: as Player

:Time: as Time
:Opponent: as Opp
rectangle DriftFeverGameSystem {

Player --> (Change game settings)


Player --> (View garage)  
(View garage) <.. (Equip car upgrades) : <extends>
(View garage) <.. (Unequip car upgrades) : <extends>
(View garage) <.left. (Fix broken down car) : <extends>
(View garage) <.right. (Change car for racing) : <extends>
(View garage) <.. (Fill up car's fuel tank) : <extends>

Player --> (View shop)
(View shop) <.. (Sell items) : <extends>
(View shop) <.. (Purchase items) : <extends>



Player --> (Begin game)
(Begin game) .-left.> (Select a race) : <include>
(Begin game) <.. (Retire from race) : <extends>
(Begin game) <.. (Pickup hitchhiker during race) : <extends>
(Begin game) <.. (Fill up fuel tank during race) : <extends>


Time --> (Update race animation)
Time --> (Trigger a random popup event)

Opp --> (Race against other players)

}





@enduml